version: "3.7"

services:
  zookeeper:
    build: docker/zookeeper
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  brokers:
    depends_on:
      - zookeeper
    build: docker/brokers
    image: brokers
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=KAFKA://brokers:9093,KAFKA_HOST://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=KAFKA
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=KAFKA:PLAINTEXT,KAFKA_HOST:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

  geoserver:
    depends_on:
      - brokers
    build: docker/geoserver
    image: geoserver
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_HOME=/geoserver
    volumes:
      - $PWD/geoserver:/geoserver
    command: sh /geoserver/bin/startup.sh
